//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public long Country { get; set; }
        public long State { get; set; }
        public string Gender { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual State State1 { get; set; }
    }
}
