//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public long StateId { get; set; }
        public string StateName { get; set; }
        public long Country { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
